// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3xgB94EczGysg6kNUEieRvT_hZj2Rhos',
    appId: '1:530808222743:web:e82ccb26e60597f20b5852',
    messagingSenderId: '530808222743',
    projectId: 'notex007-1611c',
    authDomain: 'notex007-1611c.firebaseapp.com',
    storageBucket: 'notex007-1611c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO9CKAl2odKZkVObu-9nz9_fcpeLJtnk8',
    appId: '1:530808222743:android:1000d0696257f22b0b5852',
    messagingSenderId: '530808222743',
    projectId: 'notex007-1611c',
    storageBucket: 'notex007-1611c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxYdo2cuZO26Tm3wlWSeql-wfZYte1O-Y',
    appId: '1:530808222743:ios:ba51b090d06c4e4d0b5852',
    messagingSenderId: '530808222743',
    projectId: 'notex007-1611c',
    storageBucket: 'notex007-1611c.firebasestorage.app',
    iosBundleId: 'com.example.noteManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxYdo2cuZO26Tm3wlWSeql-wfZYte1O-Y',
    appId: '1:530808222743:ios:ba51b090d06c4e4d0b5852',
    messagingSenderId: '530808222743',
    projectId: 'notex007-1611c',
    storageBucket: 'notex007-1611c.firebasestorage.app',
    iosBundleId: 'com.example.noteManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3xgB94EczGysg6kNUEieRvT_hZj2Rhos',
    appId: '1:530808222743:web:cd24c676934c0d970b5852',
    messagingSenderId: '530808222743',
    projectId: 'notex007-1611c',
    authDomain: 'notex007-1611c.firebaseapp.com',
    storageBucket: 'notex007-1611c.firebasestorage.app',
  );
}
